# EscadiaHax Configuration
# A professional anti-cheat plugin with advanced detection capabilities

# X-ray detection settings
xray-detection:
  # The minimum suspicion score required to trigger a notification
  min-suspicion-score-for-notification: 50
  # Weight factors for different detection metrics
  weights:
    valuable-ore-ratio: 10
    suspicious-enchants: 5
    mining-patterns: 20
    impossible-enchants: 10
    direct-mining: 15
    unnatural-speed: 15
  # Debug settings
  debug:
    # Enable detailed logging for detection decisions
    detailed-logging: false
    # Debug level (0=off, 1=important only, 2=detailed)
    debug-level: 0
    # Only log high suspicion scores
    log-only-high-suspicion: true
    # Minimum suspicion score to log (if log-only-high-suspicion is true)
    min-score-to-log: 40
  # Advanced detection settings
  advanced:
    # Allow higher ratios of valuable ores when mining in natural caves (Y level below this is considered a cave)
    cave-y-level: 50
    # Allow higher ratios for players with Fortune enchantment
    fortune-allowance:
      enabled: true
      # Each level of Fortune multiplies the allowable valuable ore ratio by this amount
      multiplier: 1.5
    # Environmental context detection
    context-detection:
      enabled: true
      # If a player is near lava/water, they're more likely to be in a cave, so reduce suspicion
      lava-water-detection-radius: 5
      # Exposed ore blocks are more likely in caves (multiple sides not surrounded by solid blocks)
      check-exposed-faces: true
      # Reduce suspicion if player is mining near other players (cooperative mining)
      cooperative-mining-radius: 20
      # Vein detection settings
      vein-detection:
        enabled: true
        # Maximum distance between blocks to be considered part of the same vein
        max-distance: 3
      # Mining speed detection
      speed-detection:
        enabled: true
        # Minimum time between block breaks (in milliseconds) to be considered natural
        min-break-time: 200
      # Natural cave detection
      cave-detection:
        enabled: true
        # Percentage of air blocks required to consider an area a natural cave
        air-percentage-threshold: 40
      # Ore cluster detection 
      cluster-detection:
        enabled: true
        # Minimum number of ore blocks nearby to be considered a natural cluster
        min-nearby-ores: 1

# Notification settings
notifications:
  # Enable or disable staff notifications
  enabled: true
  # Log suspicious activities to console
  log-to-console: true
  # Show detailed information in notifications
  show-details: true
  # Cooldown between notifications about the same player (in seconds)
  cooldown-seconds: 60
  # Notification format
  # Available placeholders: %player%, %score%
  format: "§c[EscadiaHax] §fPlayer §e%player% §fis showing suspicious behavior (Score: §c%score%§f)"

# GUI settings
gui:
  # Title of the suspicious players GUI
  title: "§c§lSuspicious Players"
  # Minimum suspicion score to appear in the GUI
  min-score: 30
  # Refresh rate of the GUI (in seconds)
  refresh-rate: 30
  # Message shown when a player is marked as checked
  checked-message: "§a[EscadiaHax] §fMarked §e%player% §fas checked. Removed from suspicious players list."
  # Message shown when a player's checked status is reset
  reset-checked-message: "§a[EscadiaHax] §fReset checked status for §e%player%§f."

# Vanish settings
vanish:
  # Give night vision effect when vanished
  night-vision: true
  # Set player to spectator mode when vanished
  spectator-mode: true

# Replay mode settings
replay:
  # Enable or disable replay functionality
  enabled: true
  # Maximum duration of a replay in seconds (strictly enforced)
  max-duration: 60
  # Number of mining sessions to record per player
  max-sessions-per-player: 5
  # Storage time for replay data in minutes (after this time, old data will be purged)
  storage-time: 60
  # Enable debug logging for replay functionality
  debug-mode: false
  # Debug level (0=off, 1=important only, 2=detailed)
  debug-level: 0
  # Only log important replay events (session start/end)
  log-minimal: true
  # Blocks to highlight in replay mode
  highlight-blocks:
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - ANCIENT_DEBRIS
